version: '3'
services:
  discover-server:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "8.0"
    tty: true
    volumes:
      - ../:/workspaces/discover-server
      - ~/.ssh:/home/vscode/.ssh
    user: vscode